[package]
name = "ffmpeg_scripts_rust"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "chapter-add"
path = "src/bin/chapter-add.rs"

[[bin]]
name = "chapter-csv"
path = "src/bin/chapter-csv.rs"

[[bin]]
name = "chapter-extract"
path = "src/bin/chapter-extract.rs"

[[bin]]
name = "contact-sheet"
path = "src/bin/contact-sheet.rs"

[[bin]]
name = "extract-frame"
path = "src/bin/extract-frame.rs"

[[bin]]
name = "scopes"
path = "src/bin/scopes.rs"

[[bin]]
name = "sexagesimal-time"
path = "src/bin/sexagesimal-time.rs"

[[bin]]
name = "trim-clip"
path = "src/bin/trim-clip.rs"

[[bin]]
name = "trim-clip-to"
path = "src/bin/trim-clip-to.rs"

[[bin]]
name = "trim-remote-clip"
path = "src/bin/trim-remote-clip.rs"

[[bin]]
name = "waveform"
path = "src/bin/waveform.rs"

[[bin]]
name = "webp"
path = "src/bin/webp.rs"

[[bin]]
name = "vid2gif"
path = "src/bin/vid2gif.rs"

[[bin]]
name = "ebu-meter"
path = "src/bin/ebu-meter.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }