[package]
name = "ffmpeg_scripts_rust"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "audio-silence"
path = "src/bin/audio-silence.rs"

[[bin]]
name = "chapter-add"
path = "src/bin/chapter-add.rs"

[[bin]]
name = "chapter-csv"
path = "src/bin/chapter-csv.rs"

[[bin]]
name = "chapter-extract"
path = "src/bin/chapter-extract.rs"

[[bin]]
name = "combine-clips"
path = "src/bin/combine-clips.rs"

[[bin]]
name = "contact-sheet"
path = "src/bin/contact-sheet.rs"

[[bin]]
name = "ebu-meter"
path = "src/bin/ebu-meter.rs"

[[bin]]
name = "extract-frame"
path = "src/bin/extract-frame.rs"

[[bin]]
name = "fade-clip"
path = "src/bin/fade-clip.rs"

[[bin]]
name = "img2video"
path = "src/bin/img2video.rs"

[[bin]]
name = "overlay-clip"
path = "src/bin/overlay-clip.rs"

[[bin]]
name = "overlay-pip"
path = "src/bin/overlay-pip.rs"

[[bin]]
name = "pan-scan"
path = "src/bin/pan-scan.rs"

[[bin]]
name = "scopes"
path = "src/bin/scopes.rs"

[[bin]]
name = "sexagesimal-time"
path = "src/bin/sexagesimal-time.rs"

[[bin]]
name = "subtitle-add"
path = "src/bin/subtitle-add.rs"

[[bin]]
name = "trim-clip"
path = "src/bin/trim-clip.rs"

[[bin]]
name = "trim-clip-to"
path = "src/bin/trim-clip-to.rs"

[[bin]]
name = "trim-remote-clip"
path = "src/bin/trim-remote-clip.rs"

[[bin]]
name = "scene-cut"
path = "src/bin/scene-cut.rs"

[[bin]]
name = "scene-detect"
path = "src/bin/scene-detect.rs"

[[bin]]
name = "scene-images"
path = "src/bin/scene-images.rs"

[[bin]]
name = "trim-short"
path = "src/bin/trim-short.rs"

[[bin]]
name = "waveform"
path = "src/bin/waveform.rs"

[[bin]]
name = "webp"
path = "src/bin/webp.rs"

[[bin]]
name = "vid2gif"
path = "src/bin/vid2gif.rs"

[[bin]]
name = "xfade"
path = "src/bin/xfade.rs"

[[bin]]
name = "zoompan"
path = "src/bin/zoompan.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }